CREATE TABLE IF NOT EXISTS bulletins (
    id SERIAL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    author VARCHAR(10) NOT NULL,
    content TEXT NOT NULL,
    password VARCHAR(255) NOT NULL,
    views INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NULL,
    deleted BOOLEAN DEFAULT FALSE NOT NULL
);
